### ISSUE TITLE
Cookie law?

### ISSUE THREAD

**Issue by willwade** [AceCentre/acecentre.org.uk#271]
Can't believe I'm asking this. I personally have a blocker to avoid the darn cookie notice. But do we need to display a hideous cookie notice? https://www.cookielaw.org/the-cookie-law/

**Comment by gavinhenderson** [comment]
Urgh yeah your right I need to think about this :(

Its a while since i've done one so ill need to read up on the specifics

**Comment by gavinhenderson** [comment]
So the result of my research is that we can maybe get away without a banner. 

The law is that you only need a banner if you use cookies that are not required to use the website. So if we only use, login and cart cookies then we should be fine.

If we want google analytics we need a banner. But im thinking we maybe drop google analytics and use netlify analytics instead, which is cookieless?

If we need to build in cookie consent we will have to use a third party 'consent management platform' because its really complicated and would be impossible to manage on our own. Now a days you have to give fine grained control over the cookie consent and people need to be able change their consent later.

@willwade Whats your thoughts on that?

**Comment by willwade** [comment]
Yep. Don't do google analytics. It's overkill. Stick with netlify and bonus = no need for hideous cookie stuff. One thing though. We'd probably be wise extending/editing our privacy policy page to detail the cookies and third parties we use.
